### ISSUE TITLE
Error: Database was built with a different version of diamond as is incompatible.

### ISSUE THREAD

**Issue by jdmmans** [tseemann/phastaf#2]
Hi, I get this error whenever I try and run phastaf despite --check showing the following

Using any2fasta - /home/jmmans/.conda/envs/any2fasta/bin/any2fasta | any2fasta 0.4.2
[phastaf] Using bedtools - /usr/local/easybuild/software/BEDTools/2.25.0-intel-2016.u3/bin/bedtools | bedtools v2.25.0
[phastaf] Using diamond - /usr/local/easybuild/software/diamond/0.9.10/diamond | diamond version 0.9.10
[phastaf] Using sort - /usr/bin/sort | sort (GNU coreutils) 8.22

am I missing something? Cheers

**Comment by tseemann** [comment]
What's the error in the text above?

**Comment by jdmmans** [comment]
This is the entire text  
You ran: /home/jmmans/phastaf/bin/phastaf --outdir /data/cephfs/punim0599/Jesse/emm75/phastaf/ASM223829v1 ASM223829v1.fa --force
[phastaf] This is phastaf 0.1.0
[phastaf] Written by Torsten Seemann et al
[phastaf] Homepage is https://github.com/tseemann/phastaf
[phastaf] Operating system is linux
[phastaf] Perl version is v5.26.2
[phastaf] Machine has 32 CPU cores
[phastaf] Using any2fasta - /home/jmmans/.conda/envs/any2fasta/bin/any2fasta | any2fasta 0.4.2
[phastaf] Using bedtools - /usr/local/easybuild/software/BEDTools/2.28.0-spartan_intel-2017.u2/bin/bedtools | bedtools v2.28.0
[phastaf] Using diamond - /usr/local/easybuild/software/diamond/0.9.10/diamond | diamond version 0.9.10
[phastaf] Using sort - /usr/bin/sort | sort (GNU coreutils) 8.22
[phastaf] Forced overwrite of existing --outdir /data/cephfs/punim0599/Jesse/emm75/phastaf/ASM223829v1
[phastaf] Changing into folder: /data/cephfs/punim0599/Jesse/emm75/phastaf/ASM223829v1
[phastaf] Running: (any2fasta /data/cephfs/punim0599/Jesse/emm75/contigs/ASM223829v1.fa > contigs.fna) 2>&1 | sed 's/^/[any2fasta] /' | tee -a phastaf.log
[any2fasta] This is any2fasta 0.4.2
[any2fasta] Opening '/data/cephfs/punim0599/Jesse/emm75/contigs/ASM223829v1.fa'
[any2fasta] Detected FASTA format
[any2fasta] Read 30774 lines from '/data/cephfs/punim0599/Jesse/emm75/contigs/ASM223829v1.fa'
[any2fasta] Wrote 1 sequences from FASTA file.
[any2fasta] Processed 1 files.
[any2fasta] Done.
[phastaf] Running: (diamond blastx --threads 1 --query contigs.fna --db /home/jmmans/phastaf/db/phastaf.dmnd --id 75 --outfmt 6 qseqid qstart qend sseqid pident -k 0 --evalue 1E-6 --query-gencode 11 > diamond.coords) 2>&1 | sed 's/^/[diamond] /' | tee -a phastaf.log
[diamond] Error: Database was built with a different version of diamond as is incompatible.
[phastaf] Running: (bedtools merge -i diamond.coords.bed -d 2000 -c 1 -o count > phage.bed) 2>&1 | sed 's/^/[bedtools] /' | tee -a phastaf.log
[bedtools] 
[bedtools] *****
[bedtools] ***** ERROR: Requested column 1, but database file diamond.coords.bed only has fields 1 - 0.
[phastaf] Wrote: phage.bed
[phastaf] Walltime used: 0 min 0 sec
[phastaf] Have a suggestion for phastaf? Tell me at https://github.com/tseemann/phastaf/issues
[phastaf] Done.

**Comment by tseemann** [comment]
Your diamond version is old.
I am currently on `diamond version 0.9.25`. 
Can you upgrade?

**Comment by jdmmans** [comment]
not technically, but I could create a conda environ with a newer version so ehh. 
Works fine with diamond 0.9.25 though, maybe chuck that in the dependencies bit? 
Anyway thanks for the help

**Comment by tseemann** [comment]
Ideally I will require the user to build the database at install time, so it is compatible with whichever version you have installed.

`phastaf` is still highly experimental, as @JA-Lacey will tell you :)

**Comment by JChristopherEllis** [comment]
I keep installing and uninstalling diamond from conda because it is only downloading the old version 0.9.14.115

Am I doing something wrong?

conda install -c bioconda diamond
