### ISSUE TITLE
Fourth column in phage.bed

### ISSUE THREAD

**Issue by alipirani88** [tseemann/phastaf#3]
What does the fourth column in phage.bed file indicate?

**Comment by tseemann** [comment]
That column is meant to be the number of genes in that region
BUT
It is buggy and is counting genes multiple times when it shouldn't.

It will be fixed eventually.  CC: @JA-Lacey

**Comment by alipirani88** [comment]
Thanks @tseemann That answers my question. I will be looking forward to the next update.
